/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "var(--surface)",
        "surface-dim": "var(--surface-secondary)",
        "surface-bright": "var(--surface-elevated)",
        "surface-container-lowest": "var(--surface-elevated)",
        "surface-container-low": "var(--surface-secondary)",
        "surface-container": "var(--surface)",
        "surface-container-high": "var(--surface-secondary)",
        "surface-container-highest": "var(--border)",
        "on-surface": "var(--text-primary)",
        "on-surface-variant": "var(--text-secondary)",
        "inverse-surface": "var(--text-primary)",
        "inverse-on-surface": "var(--background)",
        "outline": "var(--text-muted)",
        "outline-variant": "var(--border-subtle)",
        "surface-tint": "var(--accent)",
        "primary": "var(--text-primary)",
        "on-primary": "var(--background)",
        "primary-container": "var(--button-background)",
        "on-primary-container": "var(--button-text)",
        "inverse-primary": "var(--accent-secondary)",
        "primary-fixed": "var(--accent)",
        "primary-fixed-dim": "var(--accent-secondary)",
        "on-primary-fixed": "var(--button-text)",
        "on-primary-fixed-variant": "var(--text-secondary)",
        "secondary": "var(--success)",
        "on-secondary": "var(--surface)",
        "secondary-container": "var(--border-subtle)",
        "on-secondary-container": "var(--success)",
        "secondary-fixed": "var(--success)",
        "secondary-fixed-dim": "var(--success)",
        "on-secondary-fixed": "var(--text-primary)",
        "on-secondary-fixed-variant": "var(--text-secondary)",
        "tertiary": "var(--warning)",
        "on-tertiary": "var(--surface)",
        "tertiary-container": "var(--border-subtle)",
        "on-tertiary-container": "var(--warning)",
        "tertiary-fixed": "var(--warning)",
        "tertiary-fixed-dim": "var(--warning)",
        "on-tertiary-fixed": "var(--text-primary)",
        "on-tertiary-fixed-variant": "var(--text-secondary)",
        "error": "var(--danger)",
        "on-error": "var(--surface)",
        "error-container": "var(--border-subtle)",
        "on-error-container": "var(--danger)",
        "background": "var(--background)",
        "on-background": "var(--text-primary)",
        "surface-variant": "var(--surface-secondary)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "panel-gap": "20px",
        "container-max": "1440px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "data-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "data-mono": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "data-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["11px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
